/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package japhiroto;

import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;


/**
 *
 * @author janbo
 */
public class Kasse_GUI extends javax.swing.JFrame {

    private Kasse_Verwaltung dieKasse_Verwaltung;
    private String aktuellesTextfeld = "txfArtikelNr";
    private ArrayList<Artikel> artikelliste;
    private boolean bezahlt=false;
    private double gegeben=0;
    private DecimalFormat df = new DecimalFormat("0.00");
    /**
     * Creates new form Kasse_GUI
     */
    public Kasse_GUI() {    

        try{
            initComponents();
            artikelliste = new ArrayList<Artikel>();
            dieKasse_Verwaltung = new Kasse_Verwaltung();
            Font font = new Font("Monospaced",Font.PLAIN, 11);
            txaAusgabe.setFont(font);
            
        } catch(SQLException e){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Fehler beim Initialisieren!", "Fehler" , JOptionPane.ERROR_MESSAGE);
        } catch(IOException e){
            getToolkit().beep();
            JOptionPane.showMessageDialog(rootPane, "Fehler beim Initialisieren!", "Fehler" , JOptionPane.ERROR_MESSAGE);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgWarten = new javax.swing.JDialog();
        pnlWarten = new javax.swing.JPanel();
        lblWarten = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAusgabe = new javax.swing.JTextArea();
        lblArtikelliste = new javax.swing.JLabel();
        txfArtikelNr = new javax.swing.JTextField();
        lblArtikelNr = new javax.swing.JLabel();
        lblAnzahl = new javax.swing.JLabel();
        txfAnzahl = new javax.swing.JTextField();
        btnHinzufuegen = new javax.swing.JButton();
        btnBezahlen = new javax.swing.JButton();
        lblGegeben = new javax.swing.JLabel();
        txfGegeben = new javax.swing.JTextField();
        lblZurueck = new javax.swing.JLabel();
        txfZurueck = new javax.swing.JTextField();
        btnStorno = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnKarte = new javax.swing.JButton();
        btnBonDrucken = new javax.swing.JButton();
        btnZifferEins = new javax.swing.JButton();
        btnZifferDrei = new javax.swing.JButton();
        btnZifferSechs = new javax.swing.JButton();
        btnZifferFünf = new javax.swing.JButton();
        btnZifferVier = new javax.swing.JButton();
        btnZifferZwei = new javax.swing.JButton();
        btnZifferAcht = new javax.swing.JButton();
        btnZifferNeun = new javax.swing.JButton();
        btnZifferNull = new javax.swing.JButton();
        btnZifferKomma = new javax.swing.JButton();
        btnZifferSieben = new javax.swing.JButton();
        btnKaufvorgangAbbrechen = new javax.swing.JButton();
        btnAuskunft = new javax.swing.JButton();
        lblGesamt = new javax.swing.JLabel();
        txfGesamt = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        lblImpressum = new javax.swing.JLabel();
        btnNeuerKaufvorgang = new javax.swing.JButton();
        txfMinus = new javax.swing.JTextField();
        lblMinusBetrag = new javax.swing.JLabel();
        btnZifferLoeschen = new javax.swing.JButton();

        dlgWarten.setTitle("bitte warten");

        lblWarten.setText("bitte warten bis Bezahlvorgang am Terminal beendet ist...");

        javax.swing.GroupLayout pnlWartenLayout = new javax.swing.GroupLayout(pnlWarten);
        pnlWarten.setLayout(pnlWartenLayout);
        pnlWartenLayout.setHorizontalGroup(
            pnlWartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWartenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWarten)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        pnlWartenLayout.setVerticalGroup(
            pnlWartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWartenLayout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(lblWarten)
                .addContainerGap())
        );

        javax.swing.GroupLayout dlgWartenLayout = new javax.swing.GroupLayout(dlgWarten.getContentPane());
        dlgWarten.getContentPane().setLayout(dlgWartenLayout);
        dlgWartenLayout.setHorizontalGroup(
            dlgWartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWarten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dlgWartenLayout.setVerticalGroup(
            dlgWartenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWarten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kasse");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txaAusgabe.setEditable(false);
        txaAusgabe.setColumns(20);
        txaAusgabe.setRows(5);
        txaAusgabe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txaAusgabe);

        lblArtikelliste.setText("Artikelliste:");

        txfArtikelNr.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txfArtikelNr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfArtikelNrMouseClicked(evt);
            }
        });

        lblArtikelNr.setText("Artikel-Nr.:");

        lblAnzahl.setText("Anzahl:");

        txfAnzahl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfAnzahlMouseClicked(evt);
            }
        });

        btnHinzufuegen.setBackground(new java.awt.Color(51, 255, 51));
        btnHinzufuegen.setText("Hinzufügen");
        btnHinzufuegen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHinzufuegenActionPerformed(evt);
            }
        });

        btnBezahlen.setBackground(new java.awt.Color(0, 204, 0));
        btnBezahlen.setText("Bar bezahlen");
        btnBezahlen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBezahlen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBezahlenActionPerformed(evt);
            }
        });

        lblGegeben.setText("Gegeben:");

        txfGegeben.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfGegebenMouseClicked(evt);
            }
        });

        lblZurueck.setText("Zurück:");

        txfZurueck.setEditable(false);

        btnStorno.setBackground(new java.awt.Color(255, 255, 51));
        btnStorno.setText("Storno");
        btnStorno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStornoActionPerformed(evt);
            }
        });

        btnMinus.setBackground(new java.awt.Color(255, 255, 51));
        btnMinus.setText("Minus");
        btnMinus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnKarte.setBackground(new java.awt.Color(0, 204, 0));
        btnKarte.setText("EC - Karte");
        btnKarte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKarteActionPerformed(evt);
            }
        });

        btnBonDrucken.setBackground(new java.awt.Color(51, 255, 51));
        btnBonDrucken.setText("Bon drucken");
        btnBonDrucken.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBonDrucken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBonDruckenActionPerformed(evt);
            }
        });

        btnZifferEins.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferEins.setText("1");
        btnZifferEins.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferEins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferEinsActionPerformed(evt);
            }
        });

        btnZifferDrei.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferDrei.setText("3");
        btnZifferDrei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferDrei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferDreiActionPerformed(evt);
            }
        });

        btnZifferSechs.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferSechs.setText("6");
        btnZifferSechs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferSechs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferSechsActionPerformed(evt);
            }
        });

        btnZifferFünf.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferFünf.setText("5");
        btnZifferFünf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferFünf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferFünfActionPerformed(evt);
            }
        });

        btnZifferVier.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferVier.setText("4");
        btnZifferVier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferVier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferVierActionPerformed(evt);
            }
        });

        btnZifferZwei.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferZwei.setText("2");
        btnZifferZwei.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferZwei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferZweiActionPerformed(evt);
            }
        });

        btnZifferAcht.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferAcht.setText("8");
        btnZifferAcht.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferAcht.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferAchtActionPerformed(evt);
            }
        });

        btnZifferNeun.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferNeun.setText("9");
        btnZifferNeun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferNeun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferNeunActionPerformed(evt);
            }
        });

        btnZifferNull.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferNull.setText("0");
        btnZifferNull.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferNull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferNullActionPerformed(evt);
            }
        });

        btnZifferKomma.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferKomma.setText(",");
        btnZifferKomma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferKomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferKommaActionPerformed(evt);
            }
        });

        btnZifferSieben.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferSieben.setText("7");
        btnZifferSieben.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferSieben.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferSiebenActionPerformed(evt);
            }
        });

        btnKaufvorgangAbbrechen.setBackground(new java.awt.Color(255, 51, 51));
        btnKaufvorgangAbbrechen.setText("Kaufvorgang abbrechen");
        btnKaufvorgangAbbrechen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKaufvorgangAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaufvorgangAbbrechenActionPerformed(evt);
            }
        });

        btnAuskunft.setBackground(new java.awt.Color(51, 255, 51));
        btnAuskunft.setText("Auskunft");
        btnAuskunft.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAuskunft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuskunftActionPerformed(evt);
            }
        });

        lblGesamt.setText("Gesamt:");

        txfGesamt.setEditable(false);

        btnLogout.setBackground(new java.awt.Color(255, 51, 51));
        btnLogout.setText("Logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblImpressum.setText("© Japhiroto 2019");

        btnNeuerKaufvorgang.setBackground(new java.awt.Color(0, 204, 0));
        btnNeuerKaufvorgang.setText("Neuer Kaufvorgang");
        btnNeuerKaufvorgang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNeuerKaufvorgang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeuerKaufvorgangActionPerformed(evt);
            }
        });

        txfMinus.setBackground(new java.awt.Color(255, 255, 51));

        lblMinusBetrag.setText("Minus- Betrag:");

        btnZifferLoeschen.setBackground(new java.awt.Color(153, 153, 255));
        btnZifferLoeschen.setText("C");
        btnZifferLoeschen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnZifferLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZifferLoeschenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNeuerKaufvorgang, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblArtikelNr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblAnzahl)
                                        .addComponent(lblGegeben, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblZurueck)
                                    .addComponent(lblGesamt))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnZifferSieben, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnZifferAcht, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnZifferNeun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnZifferVier, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnZifferFünf, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnZifferSechs, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                        .addComponent(lblMinusBetrag)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txfGegeben, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                                .addComponent(txfArtikelNr, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txfAnzahl, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(txfZurueck, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txfGesamt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(89, 89, 89)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnBezahlen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAuskunft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnKarte, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnZifferEins, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnZifferZwei, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnZifferDrei, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnZifferLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnZifferNull, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnZifferKomma, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnKaufvorgangAbbrechen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblArtikelliste)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnStorno, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblImpressum)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBonDrucken, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblArtikelliste))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnNeuerKaufvorgang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnKarte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAuskunft, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBonDrucken, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKaufvorgangAbbrechen, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(btnStorno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblArtikelNr)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAnzahl)
                                    .addComponent(txfAnzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txfArtikelNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHinzufuegen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfGesamt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGesamt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGegeben)
                            .addComponent(txfGegeben, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfZurueck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBezahlen, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblZurueck))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZifferEins, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZifferZwei, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZifferLoeschen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZifferDrei, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnZifferVier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZifferFünf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnZifferSechs, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnZifferNeun, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZifferAcht, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZifferSieben, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMinusBetrag)
                                    .addComponent(txfMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnZifferKomma, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZifferNull, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(lblImpressum))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void ausgabeAktualisieren(){
        double gesamt;
        String sGesamt;
        txaAusgabe.setText("");
        txaAusgabe.setText(dieKasse_Verwaltung.kassenzettelErstellen(artikelliste));
        gesamt = dieKasse_Verwaltung.gesamtbetragBerechnen(artikelliste);
        sGesamt = df.format(gesamt);
        txfGesamt.setText(sGesamt);
    }
    private void ansageOeffnen() throws FileNotFoundException, JavaLayerException{
        dieKasse_Verwaltung.ansageOeffnen();

    }
    private void ansageSchliessen() throws FileNotFoundException, JavaLayerException{
        dieKasse_Verwaltung.ansageSchliessen();
    }
    
    
    private void btnZifferEinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferEinsActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "1");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"1");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"1");
        }
    }//GEN-LAST:event_btnZifferEinsActionPerformed

    private void txfArtikelNrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfArtikelNrMouseClicked
        aktuellesTextfeld = "txfArtikelNr";
    }//GEN-LAST:event_txfArtikelNrMouseClicked

    private void txfAnzahlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfAnzahlMouseClicked
        aktuellesTextfeld = "txfAnzahl";
    }//GEN-LAST:event_txfAnzahlMouseClicked

    private void txfGegebenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfGegebenMouseClicked
        aktuellesTextfeld = "txfGegeben";
    }//GEN-LAST:event_txfGegebenMouseClicked

    private void btnZifferZweiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferZweiActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "2");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"2");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"2");
        }
    }//GEN-LAST:event_btnZifferZweiActionPerformed

    private void btnZifferDreiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferDreiActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "3");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"3");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"3");
        }
    }//GEN-LAST:event_btnZifferDreiActionPerformed

    private void btnZifferVierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferVierActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "4");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"4");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"4");
        }
    }//GEN-LAST:event_btnZifferVierActionPerformed

    private void btnZifferFünfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferFünfActionPerformed
       // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "5");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"5");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"5");
        }
    }//GEN-LAST:event_btnZifferFünfActionPerformed

    private void btnZifferSechsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferSechsActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "6");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"6");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"6");
        }
    }//GEN-LAST:event_btnZifferSechsActionPerformed

    private void btnZifferSiebenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferSiebenActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "7");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"7");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"7");
        }
    }//GEN-LAST:event_btnZifferSiebenActionPerformed

    private void btnZifferAchtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferAchtActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "8");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"8");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"8");
        }
    }//GEN-LAST:event_btnZifferAchtActionPerformed

    private void btnZifferNeunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferNeunActionPerformed
       // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "9");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"9");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"9");
        }
    }//GEN-LAST:event_btnZifferNeunActionPerformed

    private void btnZifferNullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferNullActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ "0");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+"0");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+"0");
        }
    }//GEN-LAST:event_btnZifferNullActionPerformed

    private void btnZifferKommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferKommaActionPerformed
        // Nach Ausgewähtem Textfeld suchen
        if(aktuellesTextfeld == "txfArtikelNr"){
            txfArtikelNr.setText(txfArtikelNr.getText()+ ".");
        }
        else if(aktuellesTextfeld == "txfAnzahl"){
            txfAnzahl.setText(txfAnzahl.getText()+".");
        }
        else if(aktuellesTextfeld == "txfGegeben"){
            txfGegeben.setText(txfGegeben.getText()+".");
        }
    }//GEN-LAST:event_btnZifferKommaActionPerformed

    private void btnHinzufuegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHinzufuegenActionPerformed
        if(bezahlt == false){  
            try{
                if(txfAnzahl.getText()== "1"||txfAnzahl.getText().equals("")){
                    artikelliste.add(dieKasse_Verwaltung.artikelSuchen(txfArtikelNr.getText()));     
                    ausgabeAktualisieren();
                }
                else if(Integer.parseInt(txfAnzahl.getText())>0 && Integer.parseInt(txfAnzahl.getText())<647){
                    artikelliste.add(dieKasse_Verwaltung.artikelSuchenMitAnzahl(txfArtikelNr.getText(),Integer.parseInt(txfAnzahl.getText())));
                    ausgabeAktualisieren();
                }
                else{
                    JOptionPane.showInputDialog(rootPane, "Bitte Anzahl überprüfen. Anzahl muss zwischen 1 und 646 liegen!");
                }
                txfArtikelNr.setText("");
                txfAnzahl.setText("");

           }
           catch(SQLException e){
               JOptionPane.showInputDialog(rootPane,"Artikel nicht gefunden! Bitte Eingaben prüfen!");
           }
            catch(NumberFormatException e){
                JOptionPane.showInputDialog(rootPane, "Bitte Anzahlfeld überprüfen!");
            }
        }
        else{
            JOptionPane.showInputDialog(rootPane, "Bezahlvorgang bereits abgeschlossen! Ein Hinzufügen ist nicht mehr möglich.");
        }
    }//GEN-LAST:event_btnHinzufuegenActionPerformed

    private void btnAuskunftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuskunftActionPerformed
        Artikel derArtikel;
        try{
            derArtikel= dieKasse_Verwaltung.artikelSuchen(txfArtikelNr.getText());
            JOptionPane.showInputDialog(rootPane,"Artikelauskunft:"+"\n"+"Artikelnummer: "+derArtikel.getArtikelNummer()+"\n"+
                    "Artikelname: "+derArtikel.getName()+"\n"+
                    "Preis: "+derArtikel.getPreis()+"€");
            txfArtikelNr.setText("");
        }
        catch(SQLException e){
            JOptionPane.showInputDialog(rootPane,"Artikel nicht gefunden! Bitte Eingaben prüfen!");
        }
    }//GEN-LAST:event_btnAuskunftActionPerformed

    private void btnBezahlenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBezahlenActionPerformed
    try{    
        if(bezahlt){
            JOptionPane.showInputDialog(rootPane, "Bezahlvorgang bereits abgeschlossen!");
        }
        else{
            if(txfGegeben.getText().equals("") || Double.parseDouble(txfGegeben.getText())  < dieKasse_Verwaltung.gesamtbetragBerechnen(artikelliste)){
                JOptionPane.showInputDialog(rootPane, "Bitte Gegeben-Feld überprüfen!");
            }
            else{
                String sGegeben,sZurueck;
                Double zurueck,gesamt;
                gesamt = dieKasse_Verwaltung.gesamtbetragBerechnen(artikelliste);
                gegeben= Double.parseDouble(txfGegeben.getText());
                zurueck =  gegeben - gesamt;
                sZurueck = df.format(zurueck);
                sGegeben = df.format(gegeben);
                txfGegeben.setText(sGegeben);
                txfZurueck.setText(sZurueck);
                bezahlt=true;
//                dieKasse_Verwaltung.artikelAbziehen(artikelliste);
                dieKasse_Verwaltung.umsatzAktualisieren(artikelliste);
                ausgabeAktualisieren();
                txaAusgabe.setText(txaAusgabe.getText()+dieKasse_Verwaltung.kassenzettelFuss(artikelliste, gegeben));
                dieKasse_Verwaltung.soundKasse();
            }
        }
    }
    catch(NumberFormatException e){
        JOptionPane.showMessageDialog(rootPane, "Bitte Gegeben-Feld überprüfen!", "Fehler" , JOptionPane.ERROR_MESSAGE);
    }
    catch(JavaLayerException | FileNotFoundException ex){
        
    }
//    catch(SQLException | IOException ey){
//        JOptionPane.showMessageDialog(rootPane,"Fehler in der Verbindung zur Datenbank! Bitte wenden sie sich an den Systemadministrator.","Fehler", JOptionPane.ERROR_MESSAGE);
//    }
    }//GEN-LAST:event_btnBezahlenActionPerformed

    private void btnKarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKarteActionPerformed
//    try{    
        JOptionPane jop = new JOptionPane();
	jop.setMessageType(JOptionPane.INFORMATION_MESSAGE);
	jop.setMessage("Bitte warten bis Bezahlvorgang am Terminal beendet ist...");
	JDialog dialog = jop.createDialog(this, "Bitte warten");
             
        if(bezahlt){
        JOptionPane.showInputDialog(rootPane, "Bezahlvorgang bereits abgeschlossen!");
    }
    else{
        int zufallszahl;
        zufallszahl = (int)(Math.random()*100);
        txfZurueck.setText("0,00");
        txfGegeben.setText("0,00");

        new Thread(new Runnable() {
		@Override
		public void run() {
                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException e) {
                    }
                    dialog.dispose();
		}
	}).start();

	dialog.setVisible(true);          
            
        
            if (zufallszahl <=20){
                JOptionPane.showInputDialog(rootPane, "Transaktion fehlgeschlagen! Bitte erneut versuchen.");
            }
            else{
//                dieKasse_Verwaltung.artikelAbziehen(artikelliste);
                dieKasse_Verwaltung.umsatzAktualisieren(artikelliste);
                JOptionPane.showInputDialog(rootPane, "Transaktion erfolgreich! Bezahlvorgang abgeschlossen.");
                bezahlt=true;
                gegeben = dieKasse_Verwaltung.gesamtbetragBerechnen(artikelliste);
                txaAusgabe.setText(dieKasse_Verwaltung.kassenzettelErstellen(artikelliste));
                txaAusgabe.setText(txaAusgabe.getText()+dieKasse_Verwaltung.kassenzettelFuss(artikelliste, gegeben));
            }
        }
//    }
//    catch(SQLException | IOException ey){
//        JOptionPane.showMessageDialog(rootPane,"Fehler in der Verbindung zur Datenbank! Bitte wenden sie sich an den Systemadministrator.","Fehler", JOptionPane.ERROR_MESSAGE);
//    }
    }//GEN-LAST:event_btnKarteActionPerformed

    private void btnNeuerKaufvorgangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeuerKaufvorgangActionPerformed
        if(bezahlt){
            txaAusgabe.setText("");
            txfAnzahl.setText("");
            txfArtikelNr.setText("");
            txfGegeben.setText("");
            txfGesamt.setText("");
            txfZurueck.setText("");
            artikelliste.clear();
            bezahlt = false;
            gegeben = 0;
        }
        else{
            JOptionPane.showInputDialog(rootPane, "Zuerst Bezahlvorgang abschließen oder abbrechen.");
        }
    }//GEN-LAST:event_btnNeuerKaufvorgangActionPerformed

    private void btnKaufvorgangAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaufvorgangAbbrechenActionPerformed
        int antwort = JOptionPane.showConfirmDialog(null, "Abbruch", "Wollen Sie wirklich abbbrechen?", JOptionPane.YES_NO_CANCEL_OPTION);

        switch (antwort) {
            case JOptionPane.OK_OPTION:
                txaAusgabe.setText("");
                txfAnzahl.setText("");
                txfArtikelNr.setText("");
                txfGegeben.setText("");
                txfGesamt.setText("");
                txfZurueck.setText("");
                artikelliste.clear();
                bezahlt = false;
                gegeben=0;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btnKaufvorgangAbbrechenActionPerformed

    private void btnBonDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBonDruckenActionPerformed
    if(bezahlt){    
        try{    
            dieKasse_Verwaltung.kassenzettelErzeugen(artikelliste, gegeben);
        }
        catch(IOException e){
            JOptionPane.showInputDialog(rootPane, "Kassenzettel konnte nicht erstellt werden! Bitte wenden sie sich an Ihren Systemadministrator!");
        }
    }
    else{
        JOptionPane.showInputDialog(rootPane, "Zuerst Bezahlvorgang abschließen um Bon zu drucken!");
    }
    }//GEN-LAST:event_btnBonDruckenActionPerformed

    private void btnStornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStornoActionPerformed
        if(bezahlt == false){
            boolean erfolgreich=false;
            String artikelNr = txfArtikelNr.getText();
            
            for (int i = 0; i < artikelliste.size(); i++) {
                if(artikelNr.equals(artikelliste.get(i).getArtikelNummer()) && erfolgreich == false){
                    artikelliste.remove(i);
                    erfolgreich=true;
                }
            }
            if(erfolgreich == true){
                JOptionPane.showInputDialog(rootPane, "Artikel mit Nr.: "+artikelNr+" erfolgreich entfernt!");
                ausgabeAktualisieren();
                txfArtikelNr.setText("");
            }
            else{
                JOptionPane.showInputDialog(rootPane, "Artikel konnte nicht gefunden werden! Bitte Artikelfeld überprüfen.");
                ausgabeAktualisieren();
            }
        }
        else{
            JOptionPane.showInputDialog(rootPane, "Storno nach Bezahlvorgang nicht mehr möglich! Bitte an Manager werden.");
        }
    }//GEN-LAST:event_btnStornoActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        try{    
            if(bezahlt==false){
            String sMinusBetrag = txfMinus.getText();
            double minusBetrag;
            Artikel minusArtikel;
            minusBetrag = Double.parseDouble(sMinusBetrag);
            minusBetrag = minusBetrag - (2*minusBetrag);
            txfMinus.setText("");
            minusArtikel = new Artikel("Minus",minusBetrag,"0");
            artikelliste.add(minusArtikel);
            ausgabeAktualisieren();
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Bitte Minus-Feld beachten! Ggf. auf Komma achten! Richtig: . Falsch: ,","Fehler",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            ansageSchliessen();
            dieKasse_Verwaltung.umsatzAnDBsenden();
            new Login_GUI().setVisible(true);
            this.dispose();
        } catch (FileNotFoundException | JavaLayerException ex) {
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, "Keine Verbindung zur Datenbank!","Fehler",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Sound wird abgespielt, wenn dsa Fenster geöffnet wird
        try {
            ansageOeffnen();
        } catch (FileNotFoundException | JavaLayerException ex) {
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnZifferLoeschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZifferLoeschenActionPerformed
       try{  
        // Nach Ausgewähtem Textfeld suchen
           if(aktuellesTextfeld == "txfArtikelNr"){
               String text;
               CharSequence shortedText;

               text = txfArtikelNr.getText();
               shortedText = text.subSequence(0, text.length()-1);
               StringBuilder sb = new StringBuilder(shortedText.length()); 
               sb.append(shortedText);
               text = sb.toString();
               txfArtikelNr.setText(text);
           }
           else if(aktuellesTextfeld == "txfAnzahl"){
               String text;
               CharSequence shortedText;

               text = txfAnzahl.getText();
               shortedText = text.subSequence(0, text.length()-1);
               StringBuilder sb = new StringBuilder(shortedText.length()); 
               sb.append(shortedText);
               text = sb.toString();
               txfAnzahl.setText(text);
           }
           else if(aktuellesTextfeld == "txfGegeben"){
               String text;
               CharSequence shortedText;

               text = txfGegeben.getText();
               shortedText = text.subSequence(0, text.length()-1);
               StringBuilder sb = new StringBuilder(shortedText.length()); 
               sb.append(shortedText);
               text = sb.toString();
               txfGegeben.setText(text);
           }
       }
       catch(StringIndexOutOfBoundsException e){
           
       }
    }//GEN-LAST:event_btnZifferLoeschenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasse_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasse_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasse_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasse_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasse_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuskunft;
    private javax.swing.JButton btnBezahlen;
    private javax.swing.JButton btnBonDrucken;
    private javax.swing.JButton btnHinzufuegen;
    private javax.swing.JButton btnKarte;
    private javax.swing.JButton btnKaufvorgangAbbrechen;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnNeuerKaufvorgang;
    private javax.swing.JButton btnStorno;
    private javax.swing.JButton btnZifferAcht;
    private javax.swing.JButton btnZifferDrei;
    private javax.swing.JButton btnZifferEins;
    private javax.swing.JButton btnZifferFünf;
    private javax.swing.JButton btnZifferKomma;
    private javax.swing.JButton btnZifferLoeschen;
    private javax.swing.JButton btnZifferNeun;
    private javax.swing.JButton btnZifferNull;
    private javax.swing.JButton btnZifferSechs;
    private javax.swing.JButton btnZifferSieben;
    private javax.swing.JButton btnZifferVier;
    private javax.swing.JButton btnZifferZwei;
    private javax.swing.JDialog dlgWarten;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnzahl;
    private javax.swing.JLabel lblArtikelNr;
    private javax.swing.JLabel lblArtikelliste;
    private javax.swing.JLabel lblGegeben;
    private javax.swing.JLabel lblGesamt;
    private javax.swing.JLabel lblImpressum;
    private javax.swing.JLabel lblMinusBetrag;
    private javax.swing.JLabel lblWarten;
    private javax.swing.JLabel lblZurueck;
    private javax.swing.JPanel pnlWarten;
    private javax.swing.JTextArea txaAusgabe;
    private javax.swing.JTextField txfAnzahl;
    private javax.swing.JTextField txfArtikelNr;
    private javax.swing.JTextField txfGegeben;
    private javax.swing.JTextField txfGesamt;
    private javax.swing.JTextField txfMinus;
    private javax.swing.JTextField txfZurueck;
    // End of variables declaration//GEN-END:variables
}