/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package japhiroto;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author philip
 */
public class LagerBestellungenGUI extends javax.swing.JFrame {

    /**
     * Creates new form LagerBestellungenGUI
     */
    private ArrayList<Bestellung> bestellungen;
    private DB_Verbindung db;
    public LagerBestellungenGUI() {
        initComponents();
        bestellungenNeuLaden();
        try {
            db = new DB_Verbindung();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "SQL Fehler: " + ex.getMessage());
        }
    }

    private void bestellungenNeuLaden() {
        try {
            bestellungen = db.getBestellungen();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "SQL Fehler: " + ex.getMessage());
        }
        DefaultTableModel model = (DefaultTableModel) tblBestellungen.getModel();
        model.setRowCount(0);
        for (int i = 0; i < bestellungen.size(); i++) {
            model.addRow(new Object[]{bestellungen.get(i).getBestellNr(), bestellungen.get(i).getLieferant()});
        }
    }
    private void warenEingangLeeren() {
        DefaultTableModel model = (DefaultTableModel) tblWarenArtikel.getModel();
        model.setRowCount(0);
        txfWarenBestellNr.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaWareneingang = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblWarenArtikel = new javax.swing.JTable();
        lblWarenWareneingang = new javax.swing.JLabel();
        lblWarenBestellNr = new javax.swing.JLabel();
        txfWarenBestellNr = new javax.swing.JTextField();
        btnWarenEingangSpeichern = new javax.swing.JButton();
        btnWarenZuruck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBestellungen = new javax.swing.JTable();
        btnWareneingang = new javax.swing.JButton();
        btnNeuLaden = new javax.swing.JButton();

        diaWareneingang.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                diaWareneingangWindowClosed(evt);
            }
        });

        tblWarenArtikel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menge", "Artikel", "Eingang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblWarenArtikel);

        lblWarenWareneingang.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblWarenWareneingang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarenWareneingang.setText("Wareneingang");

        lblWarenBestellNr.setText("Bestellnummer:");

        txfWarenBestellNr.setEditable(false);

        btnWarenEingangSpeichern.setText("Eingang speichern");
        btnWarenEingangSpeichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarenEingangSpeichernActionPerformed(evt);
            }
        });

        btnWarenZuruck.setText("zurück");
        btnWarenZuruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWarenZuruckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaWareneingangLayout = new javax.swing.GroupLayout(diaWareneingang.getContentPane());
        diaWareneingang.getContentPane().setLayout(diaWareneingangLayout);
        diaWareneingangLayout.setHorizontalGroup(
            diaWareneingangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaWareneingangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaWareneingangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addComponent(lblWarenWareneingang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diaWareneingangLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(diaWareneingangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(diaWareneingangLayout.createSequentialGroup()
                                .addComponent(btnWarenEingangSpeichern)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnWarenZuruck))
                            .addGroup(diaWareneingangLayout.createSequentialGroup()
                                .addComponent(lblWarenBestellNr)
                                .addGap(18, 18, 18)
                                .addComponent(txfWarenBestellNr)))))
                .addContainerGap())
        );
        diaWareneingangLayout.setVerticalGroup(
            diaWareneingangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaWareneingangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWarenWareneingang)
                .addGap(5, 5, 5)
                .addGroup(diaWareneingangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWarenBestellNr)
                    .addComponent(txfWarenBestellNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diaWareneingangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWarenEingangSpeichern)
                    .addComponent(btnWarenZuruck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bestellungen");

        tblBestellungen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bestellnummer", "Lieferant"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBestellungen.getTableHeader().setReorderingAllowed(false);
        tblBestellungen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblBestellungenPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblBestellungen);

        btnWareneingang.setText("Wareneingang");
        btnWareneingang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWareneingangActionPerformed(evt);
            }
        });

        btnNeuLaden.setText("neu laden");
        btnNeuLaden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeuLadenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnWareneingang, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175)
                        .addComponent(btnNeuLaden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWareneingang)
                    .addComponent(btnNeuLaden))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBestellungenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblBestellungenPropertyChange

    }//GEN-LAST:event_tblBestellungenPropertyChange

    private void btnWareneingangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWareneingangActionPerformed
        int selectZeile = tblBestellungen.getSelectedRow();
        if (selectZeile == -1) {
            JOptionPane.showMessageDialog(this, "keine Bestellung ausgewählt!");
        }
        else {
            diaWareneingang.setVisible(true);
            diaWareneingang.setSize(380, 590);
            txfWarenBestellNr.setText(String.valueOf(selectZeile));
            DefaultTableModel model = (DefaultTableModel) tblWarenArtikel.getModel();       //aktuelle Bestellungen in Tabelle anzeigen
            for (int i = 0; i < bestellungen.get(selectZeile).getAnzahlArtikel(); i++) {
                model.addRow(new Object[]{bestellungen.get(selectZeile).anzahlArtikel(i), bestellungen.get(selectZeile).bestellterArtikel(i).getName(), 0});
            }
        }
    }//GEN-LAST:event_btnWareneingangActionPerformed

    private void btnWarenEingangSpeichernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarenEingangSpeichernActionPerformed
        int bestellung = Integer.valueOf(txfWarenBestellNr.getText());          //Auswahl welches Lager
        for (int i = 0; i < bestellungen.get(bestellung).getAnzahlArtikel(); i++) {
            String strEingang = tblWarenArtikel.getModel().getValueAt(i, 2).toString();
            int intEingang = Integer.valueOf(strEingang);
            if (intEingang > 0) {
                bestellungen.get(bestellung).artikelAngekommen(i, intEingang);
                String artNr = bestellungen.get(bestellung).bestellterArtikel(i).getArtikelNummer();
                try {
                    db.wareAngekommen(bestellungen.get(bestellung).getBestellNr(), artNr, intEingang);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "SQL Fehler: " + ex);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, "IO Fehler: " + ex);
                }
            }
        }
        warenEingangLeeren();
        bestellungenNeuLaden();
        diaWareneingang.setVisible(false);
    }//GEN-LAST:event_btnWarenEingangSpeichernActionPerformed

    private void diaWareneingangWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_diaWareneingangWindowClosed
        warenEingangLeeren();
    }//GEN-LAST:event_diaWareneingangWindowClosed

    private void btnNeuLadenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeuLadenActionPerformed
        bestellungenNeuLaden();
    }//GEN-LAST:event_btnNeuLadenActionPerformed

    private void btnWarenZuruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWarenZuruckActionPerformed
        warenEingangLeeren();
        bestellungenNeuLaden();
        diaWareneingang.setVisible(false);
    }//GEN-LAST:event_btnWarenZuruckActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LagerBestellungenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNeuLaden;
    private javax.swing.JButton btnWarenEingangSpeichern;
    private javax.swing.JButton btnWarenZuruck;
    private javax.swing.JButton btnWareneingang;
    private javax.swing.JDialog diaWareneingang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblWarenBestellNr;
    private javax.swing.JLabel lblWarenWareneingang;
    private javax.swing.JTable tblBestellungen;
    private javax.swing.JTable tblWarenArtikel;
    private javax.swing.JTextField txfWarenBestellNr;
    // End of variables declaration//GEN-END:variables
}
