/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package japhiroto;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author philip
 */
public class LagerBestellungHinzufugenGUI extends javax.swing.JFrame {

    /**
     * Creates new form LagerBestellungHinzufugenGUI
     */
    private ArrayList<Artikel> artikel;
    private ArtikelVerwaltung verwaltung;
    private BestellungVerwalten bestellung;
    public LagerBestellungHinzufugenGUI() {
        try {
            initComponents();
            diaArtikelHinzufugen.setSize(400, 300);
            artikel = new ArrayList<>();
            verwaltung = new ArtikelVerwaltung();
            bestellung = new BestellungVerwalten();
            setProperties();
        } catch (IOException ex) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Ein unbekannter Fehler ist aufgetreten.", "Fehler", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Ein Datenbank-Fehler ist aufgetreten.", "SQL-Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void setProperties(){
        //Position in der Mitte des Bildschirms
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation((int)(screenSize.getWidth() - this.getWidth()) / 2, (int)(screenSize.getHeight() - this.getHeight()) / 2);
        diaArtikelHinzufugen.setLocation((int)(screenSize.getWidth() - this.getWidth()) / 2, (int)(screenSize.getHeight() - this.getHeight()) / 2);
        
        //IconImage setzen
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Japhiroto_kurz_schwarz_16.png")));
    }
    
    private void gesuchteLeeren() {
        DefaultTableModel model;
        model = (DefaultTableModel) tblGesuchteArtikel.getModel();
        model.setRowCount(0);
    }
    private void bestellungAktualisieren() {
        DefaultTableModel model;
        model = (DefaultTableModel) tblArtikel.getModel();
        model.setRowCount(0);
        for (int i = 0; i < artikel.size(); i++) {
            Artikel aktuell;
                
            aktuell = artikel.get(i);
                
            model.addRow(new Object[]{"", aktuell.getName()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaArtikelHinzufugen = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        lblDiaArtikelNr = new javax.swing.JLabel();
        txfDiaArtikelNr = new javax.swing.JTextField();
        btnDiaSuchen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGesuchteArtikel = new javax.swing.JTable();
        btnDiaArtikelHinzufugen = new javax.swing.JButton();
        lblBestellung = new javax.swing.JLabel();
        lblBestellNr = new javax.swing.JLabel();
        lblLieferant = new javax.swing.JLabel();
        txfBestellNummer = new javax.swing.JTextField();
        txfLieferant = new javax.swing.JTextField();
        btnArtikelHinzufugen = new javax.swing.JButton();
        lblArtikel = new javax.swing.JLabel();
        btnArtikelLoschen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArtikel = new javax.swing.JTable();
        btnBestellungHinzufugen = new javax.swing.JButton();
        btnZuruck = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Artikel hinzufügen");

        lblDiaArtikelNr.setText("Artikelnummer");

        btnDiaSuchen.setText("suchen");
        btnDiaSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaSuchenActionPerformed(evt);
            }
        });

        tblGesuchteArtikel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artikelnummer", "Artikel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblGesuchteArtikel.setColumnSelectionAllowed(true);
        tblGesuchteArtikel.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblGesuchteArtikel);
        tblGesuchteArtikel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnDiaArtikelHinzufugen.setText("hinzufügen");
        btnDiaArtikelHinzufugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaArtikelHinzufugenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaArtikelHinzufugenLayout = new javax.swing.GroupLayout(diaArtikelHinzufugen.getContentPane());
        diaArtikelHinzufugen.getContentPane().setLayout(diaArtikelHinzufugenLayout);
        diaArtikelHinzufugenLayout.setHorizontalGroup(
            diaArtikelHinzufugenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaArtikelHinzufugenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaArtikelHinzufugenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(diaArtikelHinzufugenLayout.createSequentialGroup()
                        .addComponent(lblDiaArtikelNr)
                        .addGap(18, 18, 18)
                        .addGroup(diaArtikelHinzufugenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDiaSuchen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txfDiaArtikelNr)))
                    .addComponent(btnDiaArtikelHinzufugen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        diaArtikelHinzufugenLayout.setVerticalGroup(
            diaArtikelHinzufugenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaArtikelHinzufugenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(diaArtikelHinzufugenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaArtikelNr)
                    .addComponent(txfDiaArtikelNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiaSuchen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiaArtikelHinzufugen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bestellung hinzufügen");

        lblBestellung.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblBestellung.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBestellung.setText("Bestellung hinzufügen");

        lblBestellNr.setText("Bestellnummer");

        lblLieferant.setText("Lieferant");

        btnArtikelHinzufugen.setText("hinzufügen");
        btnArtikelHinzufugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtikelHinzufugenActionPerformed(evt);
            }
        });

        lblArtikel.setText("Artikel");

        btnArtikelLoschen.setText("löschen");
        btnArtikelLoschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtikelLoschenActionPerformed(evt);
            }
        });

        tblArtikel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Anzahl", "Artikel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArtikel.setColumnSelectionAllowed(true);
        tblArtikel.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblArtikel);
        tblArtikel.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblArtikel.getColumnModel().getColumnCount() > 0) {
            tblArtikel.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        btnBestellungHinzufugen.setText("Bestellung hinzufügen");
        btnBestellungHinzufugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestellungHinzufugenActionPerformed(evt);
            }
        });

        btnZuruck.setText("zurück");
        btnZuruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZuruckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBestellNr)
                            .addComponent(lblLieferant)
                            .addComponent(lblArtikel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnArtikelHinzufugen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addComponent(btnArtikelLoschen, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txfBestellNummer)
                            .addComponent(txfLieferant)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblBestellung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnBestellungHinzufugen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnZuruck)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBestellung, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBestellNr)
                    .addComponent(txfBestellNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLieferant)
                    .addComponent(txfLieferant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnArtikelHinzufugen)
                        .addComponent(btnArtikelLoschen))
                    .addComponent(lblArtikel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBestellungHinzufugen)
                    .addComponent(btnZuruck))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArtikelHinzufugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtikelHinzufugenActionPerformed
        diaArtikelHinzufugen.setVisible(true);
        diaArtikelHinzufugen.setLocation(this.getLocation());
        diaArtikelHinzufugen.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Japhiroto_kurz_schwarz_16.png")));
        diaArtikelHinzufugen.setTitle("Artikel hinzufügen");
    }//GEN-LAST:event_btnArtikelHinzufugenActionPerformed

    private void btnDiaSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaSuchenActionPerformed
        try {
            String gesuchteArtNr;
            ArrayList<Artikel> gesuchteArt;
            DefaultTableModel model;
            
            gesuchteArtNr = txfDiaArtikelNr.getText();
            model = (DefaultTableModel) tblGesuchteArtikel.getModel();
            gesuchteArt = verwaltung.getArtikelListeFromNummer(gesuchteArtNr);
            
            gesuchteLeeren();
            for (int i = 0; i < gesuchteArt.size(); i++) {
                Artikel aktuell;
                
                aktuell = gesuchteArt.get(i);
                
                model.addRow(new Object[]{aktuell.getArtikelNummer(), aktuell.getName()});
            }
        } catch (SQLException ex) {
            getToolkit().beep();
                JOptionPane.showMessageDialog(this, "Ein Datenbank-Fehler ist aufgetreten.", "SQL-Fehler", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
            getToolkit().beep();
                JOptionPane.showMessageDialog(this, "Keinen Artikel gefunden", "Fehler", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnDiaSuchenActionPerformed

    private void btnDiaArtikelHinzufugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaArtikelHinzufugenActionPerformed
        String gesuchteArtNr;
        int select;
        DefaultTableModel model;
        
        select = tblGesuchteArtikel.getSelectedRow();
        model = (DefaultTableModel) tblGesuchteArtikel.getModel();
        
        
        if (select == -1) {
           getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Es wurde kein Artikel ausgewählt.", "Auswahl-Fehler", JOptionPane.ERROR_MESSAGE);
        }
        else {
            try {
                String artNr;
                Artikel e;
                
                artNr = model.getValueAt(select, 0).toString();
                e = verwaltung.getArtikel(artNr);
                
                artikel.add(e);
            } catch (SQLException ex) {
                getToolkit().beep();
                JOptionPane.showMessageDialog(this, "Ein Datenbank-Fehler ist aufgetreten.", "SQL-Fehler", JOptionPane.ERROR_MESSAGE);
            }
            diaArtikelHinzufugen.setVisible(false);
            gesuchteLeeren();
            bestellungAktualisieren();
        }
    }//GEN-LAST:event_btnDiaArtikelHinzufugenActionPerformed

    private void btnBestellungHinzufugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestellungHinzufugenActionPerformed
        try {
            DefaultTableModel model;
            String bestellNr, lieferant;
            
            model = (DefaultTableModel) tblArtikel.getModel();
            bestellNr = txfBestellNummer.getText();
            lieferant = txfLieferant.getText();
            
            ArrayList<Artikel> test = artikel;
            
            for (int i = 0; i < artikel.size(); i++) {
                int anzahl;
                
                anzahl = Integer.valueOf(model.getValueAt(i, 0).toString());
                
                artikel.get(i).setAnzahl(anzahl);
            }
            bestellung.artikelBestellen(artikel, bestellNr, lieferant);
        } catch (SQLException ex) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Ein Datenbank-Fehler ist aufgetreten.", "SQL-Fehler", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Falsche Stückzahl der Artikel eingegeben.", "Format-Fehler", JOptionPane.ERROR_MESSAGE);
        } catch (NullPointerException ex) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Ein Fehler ist aufgetreten:\n" + ex.getMessage(), "Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBestellungHinzufugenActionPerformed

    private void btnZuruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZuruckActionPerformed
        try {
            this.setVisible(false);
            bestellung.verbindungSchliessen();
            verwaltung.verbindungSchliessen();
        } catch (SQLException ex) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Ein Datenbank-Fehler ist aufgetreten.", "DB-Fehler", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnZuruckActionPerformed

    private void btnArtikelLoschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtikelLoschenActionPerformed
        try{
            int select;
            select = tblArtikel.getSelectedRow();
        
            artikel.remove(select);
            bestellungAktualisieren();
        } catch (ArrayIndexOutOfBoundsException ex){
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Artikel zum Löschen auswählen", "Artikel wählen", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnArtikelLoschenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungHinzufugenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungHinzufugenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungHinzufugenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LagerBestellungHinzufugenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LagerBestellungHinzufugenGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArtikelHinzufugen;
    private javax.swing.JButton btnArtikelLoschen;
    private javax.swing.JButton btnBestellungHinzufugen;
    private javax.swing.JButton btnDiaArtikelHinzufugen;
    private javax.swing.JButton btnDiaSuchen;
    private javax.swing.JButton btnZuruck;
    private javax.swing.JDialog diaArtikelHinzufugen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArtikel;
    private javax.swing.JLabel lblBestellNr;
    private javax.swing.JLabel lblBestellung;
    private javax.swing.JLabel lblDiaArtikelNr;
    private javax.swing.JLabel lblLieferant;
    private javax.swing.JTable tblArtikel;
    private javax.swing.JTable tblGesuchteArtikel;
    private javax.swing.JTextField txfBestellNummer;
    private javax.swing.JTextField txfDiaArtikelNr;
    private javax.swing.JTextField txfLieferant;
    // End of variables declaration//GEN-END:variables
}
