/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package japhiroto;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author tomas.hrubec
 */
public class Marktleiter_GUI extends javax.swing.JFrame {
    
    private Graphics2D diagram;
    private int sizeX; // =500
    private int sizeY; // =400
    private int zeroX = sizeX;
    private int zeroY = sizeY;
            
    
    /**
     * Creates new form Marktleiter_GUI
     */
    public Marktleiter_GUI() {
        initComponents();
        
        diagram = (Graphics2D)cvDarstellungsfeld.getGraphics();
        sizeX = cvDarstellungsfeld.getWidth();
        sizeY = cvDarstellungsfeld.getHeight();
                        
        //set zero
        // sizeX = 500, sizeY = 400
        // zeroX = 25;
        // zeroY = 370;
               
        zeroX = sizeX - 475;
        zeroY = sizeY - 30;
                          
    }
    
//    public void paint(Graphics g) {
//        super.paint(g);
//        g.setFont(new Font("Dialog", Font.PLAIN, 18));
//        g.setColor(Color.BLUE);
//        g.drawString("Hallo Welt", 100,400);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUmsatz = new javax.swing.JLabel();
        lblMitarbeiter = new javax.swing.JLabel();
        lblAuswahl = new javax.swing.JLabel();
        scrlPanAuswahl = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        txfNummer = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblVorname = new javax.swing.JLabel();
        txfVorname = new javax.swing.JTextField();
        txfNachname = new javax.swing.JTextField();
        lblNachname = new javax.swing.JLabel();
        ComBoxDatumVon = new javax.swing.JComboBox<>();
        lblDatumauswahl = new javax.swing.JLabel();
        lblDatumVon = new javax.swing.JLabel();
        lblDatumBis = new javax.swing.JLabel();
        ComBoxDatumBis = new javax.swing.JComboBox<>();
        btnUmsAnzg = new javax.swing.JButton();
        btnProdList = new javax.swing.JButton();
        btnBestellungen = new javax.swing.JButton();
        lblStatusBestellungen = new javax.swing.JLabel();
        txfBestellt = new javax.swing.JTextField();
        btnDrucken = new javax.swing.JButton();
        lblBestellt = new javax.swing.JLabel();
        txfVerschickt = new javax.swing.JTextField();
        lblVerschickt = new javax.swing.JLabel();
        txfInBearb = new javax.swing.JTextField();
        lblInBearb = new javax.swing.JLabel();
        lblAnrede = new javax.swing.JLabel();
        txfAnrede = new javax.swing.JTextField();
        txfStrasse = new javax.swing.JTextField();
        lblStarsse = new javax.swing.JLabel();
        txfHausNr = new javax.swing.JTextField();
        lblHausNr = new javax.swing.JLabel();
        txfPLZ = new javax.swing.JTextField();
        lblPLZ = new javax.swing.JLabel();
        txfOrt = new javax.swing.JTextField();
        lblOrt = new javax.swing.JLabel();
        txfStundenlohn = new javax.swing.JTextField();
        lblStundenlohn = new javax.swing.JLabel();
        txfRolle = new javax.swing.JTextField();
        lblRolle = new javax.swing.JLabel();
        cvDarstellungsfeld = new java.awt.Canvas();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblUmsatz.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblUmsatz.setText("Umsatz- und Warenverwaltung");

        lblMitarbeiter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblMitarbeiter.setText("Mitarbeiterverwaltung");

        lblAuswahl.setText("Auswahl");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrlPanAuswahl.setViewportView(jList1);

        lblID.setText("Mitarbeiter ID");

        lblVorname.setText("Vorname");

        txfVorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfVornameActionPerformed(evt);
            }
        });

        lblNachname.setText("Nachname");

        ComBoxDatumVon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDatumauswahl.setText("Datumauswahl");

        lblDatumVon.setText("Von:");

        lblDatumBis.setText("Bis:");

        ComBoxDatumBis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComBoxDatumBis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComBoxDatumBisActionPerformed(evt);
            }
        });

        btnUmsAnzg.setText("Umsatz Anzeigen");
        btnUmsAnzg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUmsAnzgActionPerformed(evt);
            }
        });

        btnProdList.setText("Produktliste Anzeigen");
        btnProdList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdListActionPerformed(evt);
            }
        });

        btnBestellungen.setText("Bestellungen Anzeigen");
        btnBestellungen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBestellungenActionPerformed(evt);
            }
        });

        lblStatusBestellungen.setText("Status offener Bestellungen:");

        txfBestellt.setText("Anzahl");

        btnDrucken.setText("<html>  Aktuelle<br />Darstellung<br />  Drucken</html>");
        btnDrucken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDruckenActionPerformed(evt);
            }
        });

        lblBestellt.setText("Bestellt:");

        txfVerschickt.setText("Anzahl");
        txfVerschickt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfVerschicktActionPerformed(evt);
            }
        });

        lblVerschickt.setText("Verschickt:");

        txfInBearb.setText("Anzahl");
        txfInBearb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfInBearbActionPerformed(evt);
            }
        });

        lblInBearb.setText("In Bearbeitung:");

        lblAnrede.setText("Anrede");

        lblStarsse.setText("Strasse");

        txfHausNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfHausNrActionPerformed(evt);
            }
        });

        lblHausNr.setText("Haus Nr.");

        lblPLZ.setText("PLZ");

        lblOrt.setText("Ort");

        lblStundenlohn.setText("Stundenlohn");

        lblRolle.setText("Rolle");

        cvDarstellungsfeld.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(scrlPanAuswahl, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMitarbeiter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblAuswahl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStundenlohn)
                                    .addComponent(txfStundenlohn, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRolle)
                                    .addComponent(txfRolle, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblAnrede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txfAnrede, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblVorname)
                                            .addComponent(txfVorname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNachname)
                                            .addComponent(txfNachname, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStarsse)
                                            .addComponent(txfStrasse, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblHausNr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txfHausNr, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPLZ)
                                            .addComponent(txfPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblOrt)
                                            .addComponent(txfOrt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblID))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUmsatz)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDrucken, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblStatusBestellungen)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblBestellt)
                                            .addComponent(lblVerschickt)
                                            .addComponent(lblInBearb))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txfBestellt)
                                            .addComponent(txfVerschickt)
                                            .addComponent(txfInBearb)))))
                            .addComponent(btnBestellungen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProdList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUmsAnzg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComBoxDatumBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDatumauswahl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblDatumVon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblDatumBis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComBoxDatumVon, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cvDarstellungsfeld, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUmsatz)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUmsAnzg)
                                    .addComponent(lblDatumauswahl))
                                .addGap(20, 20, 20)
                                .addComponent(btnProdList)
                                .addGap(20, 20, 20)
                                .addComponent(btnBestellungen))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDatumVon)
                                    .addGap(73, 73, 73))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(ComBoxDatumVon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(ComBoxDatumBis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(lblDatumBis))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatusBestellungen)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBestellt)
                            .addComponent(txfBestellt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfVerschickt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVerschickt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfInBearb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInBearb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDrucken, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cvDarstellungsfeld, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMitarbeiter)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAuswahl)
                        .addGap(18, 18, 18)
                        .addComponent(scrlPanAuswahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAnrede)
                                .addComponent(lblID))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblVorname)
                                    .addComponent(lblNachname)
                                    .addComponent(lblStarsse)
                                    .addComponent(lblHausNr)
                                    .addComponent(lblPLZ)
                                    .addComponent(lblOrt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txfVorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfStrasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfHausNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfPLZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfOrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfAnrede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txfNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblRolle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfRolle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblStundenlohn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfStundenlohn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfVornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfVornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVornameActionPerformed

    private void ComBoxDatumBisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComBoxDatumBisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComBoxDatumBisActionPerformed

    private void btnProdListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdListActionPerformed

    private void txfVerschicktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfVerschicktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVerschicktActionPerformed

    private void txfInBearbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfInBearbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfInBearbActionPerformed

    private void txfHausNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfHausNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfHausNrActionPerformed

    private void btnBestellungenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBestellungenActionPerformed
        // TODO add your handling code here:
        // Lager BestellungenGUI aufrufen
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LagerBestellungenGUI().setVisible(true);
            }
        });           
    }//GEN-LAST:event_btnBestellungenActionPerformed

    private void btnUmsAnzgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUmsAnzgActionPerformed
        // TODO add your handling code here:
        drawSales();
    }//GEN-LAST:event_btnUmsAnzgActionPerformed

    private void btnDruckenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDruckenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDruckenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marktleiter_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marktleiter_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marktleiter_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marktleiter_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Marktleiter_GUI().setVisible(true);
            }
        });
    }
    
    private void drawSales(){  
        //testline
//        diagram.drawLine(zeroX, zeroY, sizeX, 0);    
                
        // draw axes        
        diagram.drawLine(zeroX - 10, zeroY, sizeX - 15, zeroY);
        diagram.drawLine(zeroX, sizeY - 385, zeroX, sizeY - 15);
        
        
        // draw scale 
        // X-axis
        for (int i = 1; i < sizeX/20 - 2; i++) {
            diagram.drawLine(zeroX + i*20, zeroY - 5, zeroX + i*20, zeroY + 5);
            diagram.drawString(""+i, zeroX + i*20 - 3, zeroY + 20);            
        }
        
        // Y-axis
        for (int i = 1; i < sizeY/20 - 2; i++) {
            diagram.drawLine(zeroX - 5, zeroY - i*20, zeroX + 5, zeroY - i*20);
            diagram.drawString(""+i, zeroX - 20, zeroY - i*20 + 5);
        }
        
        
    
        
    
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComBoxDatumBis;
    private javax.swing.JComboBox<String> ComBoxDatumVon;
    private javax.swing.JButton btnBestellungen;
    private javax.swing.JButton btnDrucken;
    private javax.swing.JButton btnProdList;
    private javax.swing.JButton btnUmsAnzg;
    private java.awt.Canvas cvDarstellungsfeld;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAnrede;
    private javax.swing.JLabel lblAuswahl;
    private javax.swing.JLabel lblBestellt;
    private javax.swing.JLabel lblDatumBis;
    private javax.swing.JLabel lblDatumVon;
    private javax.swing.JLabel lblDatumauswahl;
    private javax.swing.JLabel lblHausNr;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInBearb;
    private javax.swing.JLabel lblMitarbeiter;
    private javax.swing.JLabel lblNachname;
    private javax.swing.JLabel lblOrt;
    private javax.swing.JLabel lblPLZ;
    private javax.swing.JLabel lblRolle;
    private javax.swing.JLabel lblStarsse;
    private javax.swing.JLabel lblStatusBestellungen;
    private javax.swing.JLabel lblStundenlohn;
    private javax.swing.JLabel lblUmsatz;
    private javax.swing.JLabel lblVerschickt;
    private javax.swing.JLabel lblVorname;
    private javax.swing.JScrollPane scrlPanAuswahl;
    private javax.swing.JTextField txfAnrede;
    private javax.swing.JTextField txfBestellt;
    private javax.swing.JTextField txfHausNr;
    private javax.swing.JTextField txfInBearb;
    private javax.swing.JTextField txfNachname;
    private javax.swing.JTextField txfNummer;
    private javax.swing.JTextField txfOrt;
    private javax.swing.JTextField txfPLZ;
    private javax.swing.JTextField txfRolle;
    private javax.swing.JTextField txfStrasse;
    private javax.swing.JTextField txfStundenlohn;
    private javax.swing.JTextField txfVerschickt;
    private javax.swing.JTextField txfVorname;
    // End of variables declaration//GEN-END:variables
}
